config/routes.rb
Rails.application.routes.draw do
  resources :streams, :only => [:index]

  resources :feeds

  namespace :api do
    get 'streams', :to => 'streams#index'
  end

  require 'sidekiq/web'
  get "/sidekiq" => Sidekiq::Web , :anchor => false
  post "/sidekiq" => Sidekiq::Web , :anchor => false
  
  root 'streams#index'

end

app/models/feed.rb
# Feed is the tweet we get from the twitter firehose
class Feed
  include Mongoid::Document
  # Update status is moved to false once the stream has ended
  field :processed, type: Boolean, default: false
  field :update_status, type: Boolean, default: true
  field :url_index, type: Integer
  embeds_one :interaction
  belongs_to :stream

  after_create :attach_to_stream

  def attach_to_stream
  	#"http://meerkatapp.co/ncutelli/sch-9f183eea-4243-4a1f-92ba-7e88f71056ad"
  	#https://resources.meerkatapp.co/broadcasts/11cf7ead-88d9-4a08-be56-bf857a8607fa/summary
    # Check if periscope
    self.interaction.links.url.each_with_index do |url, i|
      if url.index("meerkatapp") != nil || url.index("periscope") != nil
        self.url_index = i
        self.save
        break
      end
    end
    if self.interaction.links.url[self.url_index].index("periscope") != nil
      type = "periscope"
    # Check if meerkat
    elsif self.interaction.links.url[self.url_index].index("meerkatapp") != nil
      type = "meerkat"
    end
    if type != nil
  		stream_id = self.interaction.links.url[self.url_index].match(/[^\/]*$/).to_s

      AttachStreamWorker.perform_async(stream_id, self.id.to_s, type)
    end
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy]

  # GET /feeds
  # GET /feeds.json
  def index
    @feeds = Feed.all
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
  end

  # GET /feeds/new
  def new
    @feed = Feed.new
  end

  # GET /feeds/1/edit
  def edit
  end

  # POST /feeds
  # POST /feeds.json
  def create
    @feed = Feed.new(feed_params)

    respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
        format.json { render :show, status: :created, location: @feed }
      else
        format.html { render :new }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feeds/1
  # PATCH/PUT /feeds/1.json
  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: 'Feed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feed
      @feed = Feed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feed_params
      params.require(:feed).permit(:author, :thumbnail, :stream_link)
    end
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_form.html.haml
= form_for @feed do |f|
  - if @feed.errors.any?
    #error_explanation
      %h2= "#{pluralize(@feed.errors.count, "error")} prohibited this feed from being saved:"
      %ul
        - @feed.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :author
    = f.text_field :author
  .field
    = f.label :thumbnail
    = f.text_field :thumbnail
  .field
    = f.label :stream_link
    = f.text_field :stream_link
  .actions
    = f.submit 'Save'

app/views/feeds/edit.html.haml
%h1 Editing feed

= render 'form'

= link_to 'Show', @feed
\|
= link_to 'Back', feeds_path

app/views/feeds/new.html.haml
%h1 New feed

= render 'form'

= link_to 'Back', feeds_path

app/views/feeds/show.html.haml
%p#notice= notice

%p
  %b Author:
  = @feed.author
%p
  %b Thumbnail:
  = @feed.thumbnail
%p
  %b Stream link:
  = @feed.stream_link

= link_to 'Edit', edit_feed_path(@feed)
\|
= link_to 'Back', feeds_path