config/routes.rb
Rails.application.routes.draw do
  resources :streams, :only => [:index]

  resources :feeds

  namespace :api do
    get 'streams', :to => 'streams#index'
  end

  require 'sidekiq/web'
  get "/sidekiq" => Sidekiq::Web , :anchor => false
  post "/sidekiq" => Sidekiq::Web , :anchor => false
  
  root 'streams#index'

end

app/models/stream.rb
# Stream is the actual Meerkat Object with the attached Tweet
class Stream
  include Mongoid::Document
  include Mongoid::Timestamps

  #meerkat or periscope
  field :stream_type, type: String
  field :stream_identifier, type: String
  field :cover, type: String
  field :caption, type: String
  field :location, type: String
  field :place, type: String
  field :watchers_count, type: Integer
  field :comments_count, type: Integer
  field :likes_count, type: Integer
  field :restreams_count, type: Integer
  field :activities, type: Array
  field :influencers, type: Array
  field :encores, type: String
  field :cover_images, type: Array
  field :status, type: String
  field :end_time, type: Integer
  field :tweet_id, type: String
  field :fans, type: Array
  field :likes, type: String
  field :delete, type: String
  field :playlist, type: String
  field :restreams, type: String
  field :comments, type: String
  field :watchers, type: String

  # Create aliases for meerkat objects. We want clean RAILS attributes not camel cased
  alias_attribute :likesCount, :likes_count
  alias_attribute :coverImages, :cover_images
  alias_attribute :commentsCount, :comments_count
  alias_attribute :watchersCount, :watchers_count
  alias_attribute :restreamsCount, :restreams_count
  alias_attribute :endTime, :end_time
  alias_attribute :tweetId, :tweet_id

  embeds_one :broadcaster
  has_one :feed

  index({ caption: 1 }, { sparse: true })
  index({ created_at: -1 })
  index({ stream_type: 1 })
  index({ location: 1 }, { sparse: true })
  index({ "broadcaster.name" => 1 }, { sparse: true })

  def update_stream
  	UpdateStreamStatus.perform_async(self.stream_identifier)
  end
end

app/controllers/api/streams_controller.rb
class Api::StreamsController < ApplicationController
  # before_filter :set_xhr
  # before_filter :authenticate_user!, :except => [:create]
  layout nil
  include ActionController::Live

  # Retrieve all users for the authenticating account
  #
  # @return [Users] All users for the account
  def index
    # byebug
    page = params[:page] || 0
    number_of_streams = 12
    order_by = "created_at"
    direction = "DESC"
    streams = Stream.all#where(status: "live")
    search = params[:q]
    type = params[:t]
    if type.blank? || type == "" || type == "all"
      type = "meerkat|periscope"
    end
    if search.present? && search != ""
      streams = streams.any_of({"broadcaster.name" => /#{search}/i}, {"caption" => /#{search}/i}, {"influencers" => /#{search}/i}, {"location" => /#{search}/i}).where(stream_type: /#{type}/).page(page).per(number_of_streams).order_by(order_by + ' ' + direction)
    else
      streams = streams.where(stream_type: /#{type}/).page(page).per(number_of_streams).order_by(order_by + ' ' + direction)
    end
    
    render :json => streams.map(&:as_document)
  end

  # # Streaming API to retrieve users in a stream
  # def stream
  #   response.headers['Content-Type'] = 'text/event-stream'
  #   tags = nil
  #   all_users = Appconsumer.any_in(:app_id => my_app_ids)
  #   # If tags were passed in search for users that had this tag
  #   if params[:tags].present?
  #     tags = params[:tags]
  #     # Find all tags for the users, and then select on the ID's that have a tag
  #     tagged_users = UserTag.any_in(name: tags).any_in(:appconsumer_id => all_users.map(&:id)).only(:appconsumer_id).map(&:appconsumer_id)
  #     # From our users, only keep users who have the given tag (tagged_users) 
  #     all_users = all_users.any_in(:id => tagged_users)
  #   end
  #   users = all_users

  #   users.each do |u|
  #     u["total_size"] = all_users.count
  #     u["picture"] = Appconsumer.find(u["_id"]).get_picture
  #     u["posts"] = Impression.any_in(:app_id => my_app_ids).where(appconsumer_id: u["_id"]).count
  #     # u["tags"] = UserTag.where(appconsumer_id: u["_id"])
  #     data = Hash.new
  #     data["data"] = u
  #     response.stream.write data.to_json
  #     response.stream.write "\n\n"
  #   end
  # ensure
  #   response.stream.close
  # end
end

app/controllers/streams_controller.rb
class StreamsController < ApplicationController
  before_action :set_stream, only: [:show, :edit, :update, :destroy]

  # GET /streams
  # GET /streams.json
  def index
    @streams = Stream.all
  end

  # GET /streams/1
  # GET /streams/1.json
  def show
  end

  # GET /streams/new
  def new
    @stream = Stream.new
  end

  # GET /streams/1/edit
  def edit
  end

  # POST /streams
  # POST /streams.json
  def create
    @stream = Stream.new(stream_params)

    respond_to do |format|
      if @stream.save
        format.html { redirect_to @stream, notice: 'Stream was successfully created.' }
        format.json { render :show, status: :created, location: @stream }
      else
        format.html { render :new }
        format.json { render json: @stream.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /streams/1
  # PATCH/PUT /streams/1.json
  def update
    respond_to do |format|
      if @stream.update(stream_params)
        format.html { redirect_to @stream, notice: 'Stream was successfully updated.' }
        format.json { render :show, status: :ok, location: @stream }
      else
        format.html { render :edit }
        format.json { render json: @stream.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /streams/1
  # DELETE /streams/1.json
  def destroy
    @stream.destroy
    respond_to do |format|
      format.html { redirect_to streams_url, notice: 'Stream was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stream
      @stream = Stream.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stream_params
      params[:stream]
    end
end

app/helpers/streams_helper.rb
module StreamsHelper
end

app/views/streams/_form.html.haml
= form_for @stream do |f|
  - if @stream.errors.any?
    #error_explanation
      %h2= "#{pluralize(@stream.errors.count, "error")} prohibited this stream from being saved:"
      %ul
        - @stream.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/streams/edit.html.haml
%h1 Editing stream

= render 'form'

= link_to 'Show', @stream
\|
= link_to 'Back', streams_path

app/views/streams/index.html.haml
.row{"ng-controller" => "meerkatSearchCtrl", "ng-keyup" => "keyup($event)"}
  %nav.top-bar{"data-topbar" => "", :role => "navigation"}
    %ul.title-area
      %li.title
        %a(ng-click="window.location.reload(true)")
          %img(src="llama_logo.jpg" width=45)
          Llama Streams

      / Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone
      %li.toggle-topbar.menu-icon
        %a{:href => "#"}
          %span Menu
    %section.top-bar-section
      / Right Nav Section
      %ul.right
        %li.has-dropdown
          %a{:href => "#"} 
            %i.fi-filter
            &nbsp;Filter
          %ul.dropdown
            %li.has-dropdown
              %a(href="#")Video type
              %ul.dropdown
                %li
                  %a(ng-class="typeSelection == 'all' ? 'selected' : ''" ng-click="selectionClick('all')")
                    all 
                    %i.fi-check(ng-show="typeSelection == 'all'")
                %li
                  %a(ng-class="typeSelection == 'meerkat' ? 'selected' : ''" ng-click="selectionClick('meerkat')")
                    meerkat
                    %i.fi-check(ng-show="typeSelection == 'meerkat'")
                %li
                  %a(ng-class="typeSelection == 'periscope' ? 'selected' : ''" ng-click="selectionClick('periscope')")
                    periscope
                    %i.fi-check(ng-show="typeSelection == 'periscope'")
                %li.divider
            %li
              %a(ng-click="resetFilters()")Reset
        / %li.active
        /   %a{:href => "mailto::info@socialrest.me"}Help

      %ul.right
        %li
          %input#mainsearch(type='text' ng-model='search' placeholder='Search streams')/
        %li
          %a.search-top.button.expand(ng-click="searchSubmit()")
            Search

           
  %section.main
    .welcome.text-center
      .title
        Find live streams curated by a team of llamas.
      %p.sub-text
        A project of passion, puns and pleasure by 
        %a(href="http://socialrest.com")
          @SocialRest
      .row
        .small-5.columns.text-right
          .fb-share-button{"data-href" => "http://llamastreams.com", "data-layout" => "button"}
        .small-5.columns.text-left
          %a.twitter-share-button{"data-count" => "none", "data-dnt" => "true", "data-hashtags" => "llamastreams", "data-related" => "socialrest", "data-text" => "A team of llamas just helped me find, browse and stream live videos.", "data-url" => "http://llamastreams.com", :href => "https://twitter.com/share"} Tweet
          :javascript
            !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');
  %section.maincontent
    %ul.small-block-grid-1.medium-block-grid-3.large-block-grid-4
      %li.small-centered(ng-repeat="stream in streams")
        .panel.small-centered.text-left
          .head(ng-class="stream.stream_type == 'meerkat' ? 'meerkat' : 'periscope'")
            .name
              {{'@' + stream.broadcaster.name}}
              
              %a(href="http://twitter.com/{{stream.broadcaster.name}}" target="_blank")
                .twicon
                  %i.fi-social-twitter 
          .profile
            .image
              %img(ng-src="{{stream.broadcaster.image}}")
            .caption
              {{stream.caption}}

          .content   
            .row
              .innerContainer(ng-click="streamClick($event, stream)")
                %img(src="{{stream.cover}}" width="100%" onerror="this.src='black_image.jpg'")
          %a(ng-show="stream.stream_type == 'meerkat'" href="http://meerkatapp.co/{{stream.broadcaster.name}}" target="_blank")
            .follow(ng-class="stream.stream_type == 'meerkat' ? 'meerkat' : 'periscope'")
              Follow
          .footer
            .location
              {{stream.location}}    
            .activity
              %i.fi-torsos-all
                {{stream.watchers_count}}
              %i.fi-comment
                {{stream.comments_count || 0}}
              %i.fi-heart
                {{stream.likes-count || 0}}
              %i.fi-share
                {{stream.restreams-count || 0}}

  / .blurlayer
  / .search
  /   %input#mainsearch(type='text' ng-model='search' placeholder='@, # or Location')
  /   .searchsubmit
  /     %i.fi-magnifying-glass(onclick="$('.searchtop').click()")



 

app/views/streams/new.html.haml
%h1 New stream

= render 'form'

= link_to 'Back', streams_path

app/views/streams/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_stream_path(@stream)
\|
= link_to 'Back', streams_path